version: '3.9'

services:
  db:
    image: mysql:8.0.35
    container_name: wp_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
      - ./app/sql/local.sql:/docker-entrypoint-initdb.d/local.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.2-fpm
    container_name: wp_php
    volumes:
      - ./app/public:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress

  nginx:
    image: nginx:1.27
    container_name: wp_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/var/www/html
    depends_on:
      - wordpress
    restart: always

volumes:
  db_data:
